# Site settings

title: "Florian Latzel"
author: "Florian Latzel"
email: "florian@latzel.io"
phone: "+49 221 61 101 24"
gpg_key: "0xC3BA4866"
head: 'Hi, ich heiße Florian👋'
description: >- # this means to ignore newlines until "baseurl:"
  Trainer, Berater, Facilitator, Coach und Überzeugungstäter 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://florian.latzel.io" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%Y-%m-%d"
date_format_now: "%Y-%m-%d %H:%M"
last_modified_at: "Zuletzt geändert"
changelog: "Changelog"  
git_repo: "https://github.com/fl3a/florian.latzel.io/"

defaults:
  -
    values:
      author: "Florian Latzel"

# Drupal like teaser
show_excerpts : true
excerpt_separator   : "<!--break-->"
read_more : "Weiterlesen"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
    #  - jekyll-my-responsive-image

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
pagination:
  enabled: true

# Plugin: Auto Pages (jekyll-paginate-v2)
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-AUTOPAGES.md
autopages:
  enabled      : true
  categories:
    enabled    : false
  collections:
    enabled    : false
  tags:
    layouts:
      - 'thema.html'
    permalink: '/thema/:tag/'
    silent: false
    slugify:
      mode: 'latin'
      case: true

# jekyll-seo-tag 
# https://github.com/jekyll/jekyll-seo-tag
lang: "de"
social:
  name: Florian Latzel
  links:
    - http://de.linkedin.com/in/florianlatzel/en
    - https://github.com/fl3a
    - http://soundcloud.com/florian-latzel
    - http://drupal.org/u/fl3a
    - http://www.xing.com/profile/Florian_Latzel

my_responsive_image:
  template: _includes/responsive-image.html

# Jekyll Picture Tag
# https://rbuchberger.github.io/jekyll_picture_tag/users/configuration/
picture:
  source: assets/imgs
  output: assets/imgs/
  suppress_warnings: false           # Default
  fast_build: false                  # Default
  ignore_missing_images: development # Default: false
  disabled: nopics                   # Default: false
  nomarkdown: true                   # Default

# Minify CSS during build
sass:
  sass_dir: _sass
  style: compressed

# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

    
include:
  - .well-known
  - .htaccess
    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- deploy.conf  
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/  
